# Generated by Django 4.2.2 on 2023-08-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TodoApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="user_id",
        ),
        migrations.AddField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
